### ISSUE TITLE
Does this work on Modded 1.12.2 servers ?

### ISSUE THREAD

**Issue by Leclowndu93150** [spawnmason/randar-master#2]
It says that the seed is incorrect

**Comment by Noctorin** [comment]
how did u even get it running

**Comment by Leclowndu93150** [comment]
it's a website

**Comment by ghost** [comment]
@Leclowndu93150 share the link please

**Comment by Leclowndu93150** [comment]
https://hobune.stream/randar/

**Comment by ghost** [comment]
> https://hobune.stream/randar/

Thanks but can it work on 1.20 or no also how do I get the coordinates and make it look badass like the videos with that heatmap

**Comment by Leclowndu93150** [comment]
idk

**Comment by ghost** [comment]
> idk

alright.
